export function BackToTop() {
  return `
    <button
      id="back-to-top"
      class="
        fixed
        bottom-24
        right-6
        hidden
        z-50
        w-14
        h-14
        rounded-full
        bg-yellow-400
        shadow-xl
        flex
        items-center
        justify-center
        hover:scale-110
        transition-all
      "
    >
      <iconify-icon
        icon="mdi:arrow-up"
        width="28"
        height="28"
        class="text-black"
      ></iconify-icon>
    </button>
  `;
}